### ISSUE TITLE
twill:build Error

### ISSUE THREAD

**Issue by OoBook** [area17/twill#1658]
## Description

When I have run command of "twill:build", returns error with **_The command "'npm' 'run' 'build'" failed._**. 

### Steps to reproduce

php artisan twill:build

### Expected result

Custom components must be built.
### Actual result

Error occurs terminal process exited.
### Versions

Twill: v2.8.3

Laravel: v8.83.13

Symfony/Process : v5.4.8

**Comment by ifox** [comment]
Hi @OoBook can you please provide the full npm error log? Thanks!

**Comment by OoBook** [comment]
> Hi @OoBook can you please provide the full npm error log? Thanks!

if it is related to symfony/process package, process file link in symfony/process package
https://github.com/symfony/process/blob/5.4/Process.php


```
⠴  Building for production.../var/www/cms_default/vendor/area17/twill/node_modules/loader-runner/lib/LoaderRunner.js:114
                        throw e;
                        ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/var/www/cms_default/vendor/area17/twill/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/var/www/cms_default/vendor/area17/twill/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/var/www/cms_default/vendor/area17/twill/node_modules/webpack/lib/NormalModule.js:471:10)
    at /var/www/cms_default/vendor/area17/twill/node_modules/webpack/lib/NormalModule.js:503:5
    at /var/www/cms_default/vendor/area17/twill/node_modules/webpack/lib/NormalModule.js:358:12
    at /var/www/cms_default/vendor/area17/twill/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/var/www/cms_default/vendor/area17/twill/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at /var/www/cms_default/vendor/area17/twill/node_modules/loader-runner/lib/LoaderRunner.js:186:6
    at context.callback (/var/www/cms_default/vendor/area17/twill/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /var/www/cms_default/vendor/area17/twill/node_modules/cache-loader/dist/index.js:240:7
    at /var/www/cms_default/vendor/area17/twill/node_modules/neo-async/async.js:2830:7
    at done (/var/www/cms_default/vendor/area17/twill/node_modules/neo-async/async.js:2865:11)
    at /var/www/cms_default/vendor/area17/twill/node_modules/neo-async/async.js:2818:7
    at Array.<anonymous> (/var/www/cms_default/vendor/area17/twill/node_modules/cache-loader/dist/index.js:229:9) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.0.0

   Symfony\Component\Process\Exception\ProcessFailedException 

  The command "npm run build" failed.

Exit Code: 1(General error)

Working directory: /var/www/cms_default/vendor/area17/twill

Output:
================


Error Output:
================

  at vendor/symfony/process/Process.php:273
    269▕      */
    270▕     public function mustRun(callable $callback = null, array $env = []): self
    271▕     {
    272▕         if (0 !== $this->run($callback, $env)) {
  ➜ 273▕             throw new ProcessFailedException($this);
    274▕         }
    275▕ 
    276▕         return $this;
    277▕     }

      +16 vendor frames 
  17  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
```

**Comment by raymondtri** [comment]
Necromancing this issue, I have been unable to get twill to compile on anything past 16, which is currently in maintenance LTS stage. The current active LTS node version is 18.

I don't think this has to do with symfony process, as I have cloned twill and I am running `npm run watch` or `npm run build` directly in the repo and I still get the error. It might have something to do with the webpack / vue cli wrapper processes, I'm not quite at the level of wizardry to easily debug those though.

```
 Building for development...

 ERROR  Failed to compile with 1 error                                                                                   12:12:30 PM
 error  in ./frontend/js/main-buckets.js

Syntax Error: Error: error:0308010C:digital envelope routines::unsupported
    at Generator.next (<anonymous>)
    at new Promise (<anonymous>)


 ERROR  Error: Build failed with errors.
Error: Build failed with errors.
    at Watching.handler (C:\Users\Ray\Sites\twill\node_modules\@vue\cli-service\lib\commands\build\index.js:207:23)
    at C:\Users\Ray\Sites\twill\node_modules\webpack\lib\Watching.js:290:9
    at eval (eval at create (C:\Users\Ray\Sites\twill\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:31:1)
```

**Comment by Jigsaw5279** [comment]
I ran into a similar issue in another project, maybe this can help:

https://stackoverflow.com/a/69699772
