### ISSUE TITLE
npm run twill-dev only 'hot' detects first change

### ISSUE THREAD

**Issue by zedee** [area17/twill#331]
Hi, I'm experiencing a weird issue when developing my own block. I'm following this advice from Spectrum forums:

https://spectrum.chat/twill/help/extending-admin-js~8e000c62-5a7b-4cc1-a3ac-81862feff335

Here's the relevant part to put you in context about what I'm doing: 

> At the moment it is possible to benefit from the blocks architecture to inject your own Vue component into the build and make them available in forms by manually adding a Vue SFC in the `resources/assets/js/blocks` folder of your application. The file needs to be called `Block<Name>.vue` and the component can then be used from your form's Blade template using `a17-block-<name>`. This component might hold values you'd want to see submitted with the rest of the form. This is something you can do by hooking into Twill's Vuex store using something like `this.$store.commit(FORM.UPDATE_FORM_FIELD, field)` where field is an object with name and value properties. You'll need to `import { FORM } from '@/store/mutations'` as well. This is still kind of a hack but actually relatively straightforward to use and has allowed us recently to build totally unique features for some of our clients.

So I followed the instructions, but `npm run twill-dev` only detects the first change I make to my own component. After first change, the script seems (and outputs) it is indeed recompiling assets, but nothing is updated on the browser.

I thought it could be browser's cache, so I tried "Hard" reload, incognito mode and even clean all history, but **nothing** changes after first code change, even though the `twill-dev` script tells it recompiled successfully.

What I'm missing or doing wrong??

**Comment by zedee** [comment]
I'm the only one that has encountered this issue? :(

**Comment by zedee** [comment]
Still no light to this issue? I'm the only one experiencing it?

Well, now something different happens, because I have npm error output when after running `npm run twill-dev` and a file changes:

```
1] [0] 
[1] [0] > @ twill-hot /home/salva/projects/2019/dlasheras/recomana-twill/site
[1] [0] > cd vendor/area17/twill && cp -R public/* ${INIT_CWD}/public
[1] [0] 
[0]  WAIT  Compiling...8:05:10 PM
[0] 
[0] /home/salva/projects/2019/dlasheras/recomana-twill/site/node_modules/webpack/lib/HotModuleReplacementPlugin.js:287
[0] 									} = compilation.getPathWithInfo(hotUpdateChunkFilename, {
[0] 									                ^
[0] 
[0] TypeError: compilation.getPathWithInfo is not a function
[0]     at compilation.hooks.additionalChunkAssets.tap (/home/salva/projects/2019/dlasheras/recomana-twill/site/node_modules/webpack/lib/HotModuleReplacementPlugin.js:287:26)
[0]     at SyncHook.eval [as call] (eval at create (/home/salva/projects/2019/dlasheras/recomana-twill/site/vendor/area17/twill/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
[0]     at SyncHook.lazyCompileHook (/home/salva/projects/2019/dlasheras/recomana-twill/site/vendor/area17/twill/node_modules/tapable/lib/Hook.js:154:20)
[0]     at hooks.optimizeTree.callAsync.err (/home/salva/projects/2019/dlasheras/recomana-twill/site/vendor/area17/twill/node_modules/webpack/lib/Compilation.js:1299:37)
[0]     at _err0 (eval at create (/home/salva/projects/2019/dlasheras/recomana-twill/site/vendor/area17/twill/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:11:1)
[0]     at _async2.default.forEach.err (/home/salva/projects/2019/dlasheras/recomana-twill/site/vendor/area17/twill/node_modules/extract-text-webpack-plugin/dist/index.js:296:11)
[0]     at /home/salva/projects/2019/dlasheras/recomana-twill/site/vendor/area17/twill/node_modules/async/dist/async.js:473:16
[0]     at iteratorCallback (/home/salva/projects/2019/dlasheras/recomana-twill/site/vendor/area17/twill/node_modules/async/dist/async.js:1064:13)
[0]     at /home/salva/projects/2019/dlasheras/recomana-twill/site/vendor/area17/twill/node_modules/async/dist/async.js:969:16
[0]     at _async2.default.forEach.err (/home/salva/projects/2019/dlasheras/recomana-twill/site/vendor/area17/twill/node_modules/extract-text-webpack-plugin/dist/index.js:274:13)
[0]     at /home/salva/projects/2019/dlasheras/recomana-twill/site/vendor/area17/twill/node_modules/async/dist/async.js:473:16
[0]     at eachOfArrayLike (/home/salva/projects/2019/dlasheras/recomana-twill/site/vendor/area17/twill/node_modules/async/dist/async.js:1057:9)
[0]     at eachOf (/home/salva/projects/2019/dlasheras/recomana-twill/site/vendor/area17/twill/node_modules/async/dist/async.js:1117:5)
[0]     at Object.eachLimit (/home/salva/projects/2019/dlasheras/recomana-twill/site/vendor/area17/twill/node_modules/async/dist/async.js:3172:5)
[0]     at _async2.default.forEach (/home/salva/projects/2019/dlasheras/recomana-twill/site/vendor/area17/twill/node_modules/extract-text-webpack-plugin/dist/index.js:226:27)
[0]     at /home/salva/projects/2019/dlasheras/recomana-twill/site/vendor/area17/twill/node_modules/async/dist/async.js:3110:16
[0] npm ERR! code ELIFECYCLE
[0] npm ERR! errno 1
[0] npm ERR! @ hot: `npm run icons && cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --disable-host-check --config=node_modules/laravel-mix/setup/webpack.config.js`
[0] npm ERR! Exit status 1
[0] npm ERR! 
[0] npm ERR! Failed at the @ hot script.
[0] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[0] 
[0] npm ERR! A complete log of this run can be found in:
[0] npm ERR!     /home/salva/.npm/_logs/2019-10-07T18_05_11_669Z-debug.log
[0] cd vendor/area17/twill && npm ci && npm run hot exited with code 1

```

It's being a pain trying to debug or develop anything as I have to `Ctrl+C` `npm run twill-dev` and run it again every time I change something :(

**Comment by Shawn-Cui** [comment]
@zedee Has you ever found any solutions to this issue?

**Comment by zedee** [comment]
> @zedee Have you ever found any solutions to this issue?

Nope. I have no idea where to start :(

**Comment by RomanBert** [comment]
Had the same problem, downgraded my webpack dependency to `4.35.3`(when it still worked) to fix the `TypeError: compilation.getPathWithInfo is not a function` issue.

**Comment by zedee** [comment]
> Had the same problem, downgraded my webpack dependency to `4.35.3`(when it still worked) to fix the `TypeError: compilation.getPathWithInfo is not a function` issue.

I will try with the downgrade.

By the way, @RomanBert have you experienced a similar issue before? I mean, you make changes to the JS code, the `npm run dev` catches your change, recompiles assets, but only catches the first change. Then, even though seems to recompile (as I see in console), scripts are not re-regenerated and I have to run `npm run dev` again.

**Comment by RomanBert** [comment]
Haven't run into anything like that before, sorry 🤷‍♂

**Comment by Shawn-Cui** [comment]
@RomanBert 
Downgrade webpack to 4.35.3 worked for me, too.
Thanks!

**Comment by zedee** [comment]
@RomanBert @Shawn-Cui 
Which `package.json` did you edit to downgrade webpack version? Your global one?

**Comment by ifox** [comment]
Hey there, it looks like this was caused at some point depending on Webpack version. Considering building is not necessary anymore for Blade powered blocks, and that we updated all of our dependencies, moving from Laravel Mix to Vue CLI, I'm going to close this, but feel free to open a new issue if you run into anything like that with our new `twill:dev` command.
