### ISSUE TITLE
Creating new item results in an error

### ISSUE THREAD

**Issue by asolopovas** [area17/twill#601]
Hi when I am trying to create new item since migrating to 2.0 I get the following error
```js
{
message: "Argument 1 passed to Illuminate\Database\Grammar::parameterize() must be of the type array, string given, called in /var/www/backend/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php on line 869"
exception: "TypeError"
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Database/Grammar.php"
line: 136
trace: [{,…}, {function: "Illuminate\Database\Query\Grammars\{closure}",…},…]
0: {,…}
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php"
line: 869
function: "parameterize"
class: "Illuminate\Database\Grammar"
type: "->"
1: {function: "Illuminate\Database\Query\Grammars\{closure}",…}
function: "Illuminate\Database\Query\Grammars\{closure}"
class: "Illuminate\Database\Query\Grammars\Grammar"
type: "->"
2: {file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Support/Collection.php", line: 638,…}
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Support/Collection.php"
line: 638
function: "array_map"
3: {,…}
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php"
line: 870
function: "map"
class: "Illuminate\Support\Collection"
type: "->"
4: {,…}
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/MySqlGrammar.php"
line: 98
function: "compileInsert"
class: "Illuminate\Database\Query\Grammars\Grammar"
type: "->"
5: {,…}
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php"
line: 899
function: "compileInsert"
class: "Illuminate\Database\Query\Grammars\MySqlGrammar"
type: "->"
6: {file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php",…}
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php"
line: 2701
function: "compileInsertGetId"
class: "Illuminate\Database\Query\Grammars\Grammar"
type: "->"
7: {file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php",…}
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php"
line: 1381
function: "insertGetId"
class: "Illuminate\Database\Query\Builder"
type: "->"
8: {file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php",…}
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php"
line: 865
function: "__call"
class: "Illuminate\Database\Eloquent\Builder"
type: "->"
9: {file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php",…}
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php"
line: 830
function: "insertAndSetId"
class: "Illuminate\Database\Eloquent\Model"
type: "->"
10: {file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php",…}
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php"
line: 693
function: "performInsert"
class: "Illuminate\Database\Eloquent\Model"
type: "->"
11: {file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php",…}
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php"
line: 767
function: "save"
class: "Illuminate\Database\Eloquent\Model"
type: "->"
12: {file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Support/helpers.php", line: 422,…}
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Support/helpers.php"
line: 422
function: "Illuminate\Database\Eloquent\{closure}"
class: "Illuminate\Database\Eloquent\Builder"
type: "->"
13: {file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php",…}
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php"
line: 768
function: "tap"
14: {file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php",…}
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php"
line: 23
function: "create"
class: "Illuminate\Database\Eloquent\Builder"
type: "->"
15: {file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php",…}
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php"
line: 1662
function: "forwardCallTo"
class: "Illuminate\Database\Eloquent\Model"
type: "->"
16: {file: "/var/www/backend/vendor/area17/twill/src/Repositories/ModuleRepository.php", line: 218,…}
file: "/var/www/backend/vendor/area17/twill/src/Repositories/ModuleRepository.php"
line: 218
function: "__call"
class: "Illuminate\Database\Eloquent\Model"
type: "->"
17: {,…}
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php"
line: 28
function: "A17\Twill\Repositories\{closure}"
class: "A17\Twill\Repositories\ModuleRepository"
type: "->"
18: {file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php",…}
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php"
line: 349
function: "transaction"
class: "Illuminate\Database\Connection"
type: "->"
19: {file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php",…}
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php"
line: 261
function: "__call"
class: "Illuminate\Database\DatabaseManager"
type: "->"
20: {file: "/var/www/backend/vendor/area17/twill/src/Repositories/ModuleRepository.php", line: 229,…}
file: "/var/www/backend/vendor/area17/twill/src/Repositories/ModuleRepository.php"
line: 229
function: "__callStatic"
class: "Illuminate\Support\Facades\Facade"
type: "::"
21: {file: "/var/www/backend/vendor/area17/twill/src/Http/Controllers/Admin/ModuleController.php",…}
file: "/var/www/backend/vendor/area17/twill/src/Http/Controllers/Admin/ModuleController.php"
line: 356
function: "create"
class: "A17\Twill\Repositories\ModuleRepository"
type: "->"
22: {function: "store", class: "A17\Twill\Http\Controllers\Admin\ModuleController", type: "->"}
function: "store"
class: "A17\Twill\Http\Controllers\Admin\ModuleController"
type: "->"
23: {file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Routing/Controller.php", line: 54,…}
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Routing/Controller.php"
line: 54
function: "call_user_func_array"
24: {file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php",…}
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php"
line: 45
function: "callAction"
class: "Illuminate\Routing\Controller"
type: "->"
25: {file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Routing/Route.php", line: 225,…}
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Routing/Route.php"
line: 225
function: "dispatch"
class: "Illuminate\Routing\ControllerDispatcher"
type: "->"
26: {file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Routing/Route.php", line: 182,…}
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Routing/Route.php"
line: 182
function: "runController"
class: "Illuminate\Routing\Route"
type: "->"
27: {file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Routing/Router.php", line: 681,…}
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Routing/Router.php"
line: 681
function: "run"
class: "Illuminate\Routing\Route"
type: "->"
28: {file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line: 128,…}
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php"
line: 128
function: "Illuminate\Routing\{closure}"
class: "Illuminate\Routing\Router"
type: "->"
29: {file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authorize.php",…}
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authorize.php"
line: 45
function: "Illuminate\Pipeline\{closure}"
class: "Illuminate\Pipeline\Pipeline"
type: "->"
30: {file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line: 167,…}
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php"
line: 167
function: "handle"
class: "Illuminate\Auth\Middleware\Authorize"
type: "->"
31: {file: "/var/www/backend/vendor/area17/twill/src/Http/Middleware/Localization.php", line: 22,…}
file: "/var/www/backend/vendor/area17/twill/src/Http/Middleware/Localization.php"
line: 22
function: "Illuminate\Pipeline\{closure}"
class: "Illuminate\Pipeline\Pipeline"
type: "->"
32: {file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line: 167,…}
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php"
line: 167
function: "handle"
class: "A17\Twill\Http\Middleware\Localization"
type: "->"
33: {file: "/var/www/backend/vendor/area17/twill/src/Http/Middleware/ValidateBackHistory.php", line: 18,…}
file: "/var/www/backend/vendor/area17/twill/src/Http/Middleware/ValidateBackHistory.php"
line: 18
function: "Illuminate\Pipeline\{closure}"
class: "Illuminate\Pipeline\Pipeline"
type: "->"
34: {file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line: 167,…}
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php"
line: 167
function: "handle"
class: "A17\Twill\Http\Middleware\ValidateBackHistory"
type: "->"
35: {file: "/var/www/backend/vendor/area17/twill/src/Http/Middleware/Impersonate.php", line: 33,…}
file: "/var/www/backend/vendor/area17/twill/src/Http/Middleware/Impersonate.php"
line: 33
function: "Illuminate\Pipeline\{closure}"
class: "Illuminate\Pipeline\Pipeline"
type: "->"
36: {file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line: 167,…}
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php"
line: 167
function: "handle"
class: "A17\Twill\Http\Middleware\Impersonate"
type: "->"
37: {file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php",…}
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php"
line: 44
function: "Illuminate\Pipeline\{closure}"
class: "Illuminate\Pipeline\Pipeline"
type: "->"
38: {file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line: 167,…}
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php"
line: 167
function: "handle"
class: "Illuminate\Auth\Middleware\Authenticate"
type: "->"
39: {,…}
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php"
line: 41
function: "Illuminate\Pipeline\{closure}"
class: "Illuminate\Pipeline\Pipeline"
type: "->"
40: {file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line: 167,…}
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php"
line: 167
function: "handle"
class: "Illuminate\Routing\Middleware\SubstituteBindings"
type: "->"
41: {,…}
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php"
line: 76
function: "Illuminate\Pipeline\{closure}"
class: "Illuminate\Pipeline\Pipeline"
type: "->"
42: {file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line: 167,…}
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php"
line: 167
function: "handle"
class: "Illuminate\Foundation\Http\Middleware\VerifyCsrfToken"
type: "->"
43: {,…}
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php"
line: 49
function: "Illuminate\Pipeline\{closure}"
class: "Illuminate\Pipeline\Pipeline"
type: "->"
44: {file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line: 167,…}
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php"
line: 167
function: "handle"
class: "Illuminate\View\Middleware\ShareErrorsFromSession"
type: "->"
45: {,…}
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php"
line: 56
function: "Illuminate\Pipeline\{closure}"
class: "Illuminate\Pipeline\Pipeline"
type: "->"
46: {file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line: 167,…}
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php"
line: 167
function: "handle"
class: "Illuminate\Session\Middleware\StartSession"
type: "->"
47: {,…}
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php"
line: 37
function: "Illuminate\Pipeline\{closure}"
class: "Illuminate\Pipeline\Pipeline"
type: "->"
48: {file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line: 167,…}
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php"
line: 167
function: "handle"
class: "Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse"
type: "->"
49: {,…}
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php"
line: 66
function: "Illuminate\Pipeline\{closure}"
class: "Illuminate\Pipeline\Pipeline"
type: "->"
50: {file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line: 167,…}
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php"
line: 167
function: "handle"
class: "Illuminate\Cookie\Middleware\EncryptCookies"
type: "->"
51: {file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line: 103,…}
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php"
line: 103
function: "Illuminate\Pipeline\{closure}"
class: "Illuminate\Pipeline\Pipeline"
type: "->"
52: {file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Routing/Router.php", line: 683,…}
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Routing/Router.php"
line: 683
function: "then"
class: "Illuminate\Pipeline\Pipeline"
type: "->"
53: {file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Routing/Router.php", line: 658,…}
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Routing/Router.php"
line: 658
function: "runRouteWithinStack"
class: "Illuminate\Routing\Router"
type: "->"
54: {file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Routing/Router.php", line: 624,…}
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Routing/Router.php"
line: 624
function: "runRoute"
class: "Illuminate\Routing\Router"
type: "->"
55: {file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Routing/Router.php", line: 613,…}
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Routing/Router.php"
line: 613
function: "dispatchToRoute"
class: "Illuminate\Routing\Router"
type: "->"
56: {file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",…}
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php"
line: 165
function: "dispatch"
class: "Illuminate\Routing\Router"
type: "->"
57: {file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line: 128,…}
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php"
line: 128
function: "Illuminate\Foundation\Http\{closure}"
class: "Illuminate\Foundation\Http\Kernel"
type: "->"
58: {,…}
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php"
line: 21
function: "Illuminate\Pipeline\{closure}"
class: "Illuminate\Pipeline\Pipeline"
type: "->"
59: {file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line: 167,…}
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php"
line: 167
function: "handle"
class: "Illuminate\Foundation\Http\Middleware\TransformsRequest"
type: "->"
60: {,…}
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php"
line: 21
function: "Illuminate\Pipeline\{closure}"
class: "Illuminate\Pipeline\Pipeline"
type: "->"
61: {file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line: 167,…}
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php"
line: 167
function: "handle"
class: "Illuminate\Foundation\Http\Middleware\TransformsRequest"
type: "->"
62: {,…}
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php"
line: 27
function: "Illuminate\Pipeline\{closure}"
class: "Illuminate\Pipeline\Pipeline"
type: "->"
63: {file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line: 167,…}
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php"
line: 167
function: "handle"
class: "Illuminate\Foundation\Http\Middleware\ValidatePostSize"
type: "->"
64: {,…}
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php"
line: 63
function: "Illuminate\Pipeline\{closure}"
class: "Illuminate\Pipeline\Pipeline"
type: "->"
65: {file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line: 167,…}
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php"
line: 167
function: "handle"
class: "Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode"
type: "->"
66: {file: "/var/www/backend/vendor/fruitcake/laravel-cors/src/HandleCors.php", line: 36,…}
file: "/var/www/backend/vendor/fruitcake/laravel-cors/src/HandleCors.php"
line: 36
function: "Illuminate\Pipeline\{closure}"
class: "Illuminate\Pipeline\Pipeline"
type: "->"
67: {file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line: 167,…}
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php"
line: 167
function: "handle"
class: "Fruitcake\Cors\HandleCors"
type: "->"
68: {file: "/var/www/backend/vendor/fideloper/proxy/src/TrustProxies.php", line: 57,…}
file: "/var/www/backend/vendor/fideloper/proxy/src/TrustProxies.php"
line: 57
function: "Illuminate\Pipeline\{closure}"
class: "Illuminate\Pipeline\Pipeline"
type: "->"
69: {file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line: 167,…}
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php"
line: 167
function: "handle"
class: "Fideloper\Proxy\TrustProxies"
type: "->"
70: {file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line: 103,…}
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php"
line: 103
function: "Illuminate\Pipeline\{closure}"
class: "Illuminate\Pipeline\Pipeline"
type: "->"
71: {file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",…}
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php"
line: 140
function: "then"
class: "Illuminate\Pipeline\Pipeline"
type: "->"
72: {file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",…}
file: "/var/www/backend/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php"
line: 109
function: "sendRequestThroughRouter"
class: "Illuminate\Foundation\Http\Kernel"
type: "->"
73: {file: "/var/www/backend/public/index.php", line: 55, function: "handle",…}
file: "/var/www/backend/public/index.php"
line: 55
function: "handle"
class: "Illuminate\Foundation\Http\Kernel"
type: "->"
}
```

**Comment by mwikala** [comment]
Also receiving this error, not too sure what the cause is.

**Comment by futurewebsites** [comment]
Hmm I am getting this error too I don't have a slug column only:

id, device_id, name, description + standard columns

```
Illuminate\Database\Grammar::parameterize(): Argument #1 ($values) must be of type array, string given, called in /home/vagrant/Code/compare/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php on line 886 {"originalException":"[object] (TypeError(code: 0): Illuminate\\Database\\Grammar::parameterize(): Argument #1 ($values) must be of type array, string given, called in /home/vagrant/Code/compare/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php on line 886 at /home/vagrant/Code/compare/vendor/laravel/framework/src/Illuminate/Database/Grammar.php:136)
[stacktrace]
#0 /home/vagrant/Code/compare/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php(886): Illuminate\\Database\\Grammar->parameterize()
#1 [internal function]: Illuminate\\Database\\Query\\Grammars\\Grammar->Illuminate\\Database\\Query\\Grammars\\{closure}()
#2 /home/vagrant/Code/compare/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(640): array_map()
#3 /home/vagrant/Code/compare/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php(887): Illuminate\\Support\\Collection->map()
#4 /home/vagrant/Code/compare/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/MySqlGrammar.php(134): Illuminate\\Database\\Query\\Grammars\\Grammar->compileInsert()
#5 /home/vagrant/Code/compare/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php(916): Illuminate\\Database\\Query\\Grammars\\MySqlGrammar->compileInsert()
#6 /home/vagrant/Code/compare/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2960): Illuminate\\Database\\Query\\Grammars\\Grammar->compileInsertGetId()
#7 /home/vagrant/Code/compare/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1641): Illuminate\\Database\\Query\\Builder->insertGetId()
#8 /home/vagrant/Code/compare/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1180): Illuminate\\Database\\Eloquent\\Builder->__call()
#9 /home/vagrant/Code/compare/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1145): Illuminate\\Database\\Eloquent\\Model->insertAndSetId()
#10 /home/vagrant/Code/compare/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(986): Illuminate\\Database\\Eloquent\\Model->performInsert()
#11 /home/vagrant/Code/compare/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(884): Illuminate\\Database\\Eloquent\\Model->save()
#12 /home/vagrant/Code/compare/vendor/laravel/framework/src/Illuminate/Support/helpers.php(263): Illuminate\\Database\\Eloquent\\Builder->Illuminate\\Database\\Eloquent\\{closure}()
#13 /home/vagrant/Code/compare/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(885): tap()
#14 /home/vagrant/Code/compare/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Illuminate\\Database\\Eloquent\\Builder->create()
#15 /home/vagrant/Code/compare/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2109): Illuminate\\Database\\Eloquent\\Model->forwardCallTo()
#16 /home/vagrant/Code/compare/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2121): Illuminate\\Database\\Eloquent\\Model->__call()
#17 /home/vagrant/Code/compare/app/Services/Transformers/BaseXmlTransformer.php(176): Illuminate\\Database\\Eloquent\\Model::__callStatic()
#18 /home/vagrant/Code/compare/app/Services/Transformers/BaseXmlTransformer.php(88): App\\Services\\Transformers\\BaseXmlTransformer->deviceVersion()
#19 /home/vagrant/Code/compare/app/Console/Commands/RefreshFeeds.php(116): App\\Services\\Transformers\\BaseXmlTransformer->transform()
#20 /home/vagrant/Code/compare/app/Services/Parsers/Xml.php(29): App\\Console\\Commands\\RefreshFeeds->App\\Console\\Commands\\{closure}()
#21 /home/vagrant/Code/compare/app/Console/Commands/RefreshFeeds.php(117): App\\Services\\Parsers\\Xml->parse()
#22 /home/vagrant/Code/compare/app/Console/Commands/RefreshFeeds.php(69): App\\Console\\Commands\\RefreshFeeds->processFeed()
#23 /home/vagrant/Code/compare/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(96): App\\Console\\Commands\\RefreshFeeds->App\\Console\\Commands\\{closure}()
#24 /home/vagrant/Code/compare/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(51): Illuminate\\Database\\Eloquent\\Builder->Illuminate\\Database\\Concerns\\{closure}()
#25 /home/vagrant/Code/compare/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(100): Illuminate\\Database\\Eloquent\\Builder->chunk()
#26 /home/vagrant/Code/compare/app/Console/Commands/RefreshFeeds.php(78): Illuminate\\Database\\Eloquent\\Builder->each()
#27 /home/vagrant/Code/compare/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Console\\Commands\\RefreshFeeds->handle()
#28 /home/vagrant/Code/compare/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#29 /home/vagrant/Code/compare/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#30 /home/vagrant/Code/compare/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#31 /home/vagrant/Code/compare/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Container\\BoundMethod::call()
#32 /home/vagrant/Code/compare/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#33 /home/vagrant/Code/compare/vendor/symfony/console/Command/Command.php(299): Illuminate\\Console\\Command->execute()
#34 /home/vagrant/Code/compare/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#35 /home/vagrant/Code/compare/vendor/symfony/console/Application.php(978): Illuminate\\Console\\Command->run()
#36 /home/vagrant/Code/compare/vendor/symfony/console/Application.php(295): Symfony\\Component\\Console\\Application->doRunCommand()
#37 /home/vagrant/Code/compare/vendor/symfony/console/Application.php(167): Symfony\\Component\\Console\\Application->doRun()
#38 /home/vagrant/Code/compare/vendor/laravel/framework/src/Illuminate/Console/Application.php(92): Symfony\\Component\\Console\\Application->run()
#39 /home/vagrant/Code/compare/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#40 /home/vagrant/Code/compare/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#41 {main}
"} 
```

**Comment by futurewebsites** [comment]
@asolopovas can you remember what the solution was for this I spectrum.chat is no more

**Comment by raz-iacob** [comment]
I also encounter this error and need some guidance on how to solve it.
