### ISSUE TITLE
shouldReplaceMedia still process $id == null

### ISSUE THREAD

**Issue by weburnit** [area17/twill#957]
### Steps to reproduce
Upload Media file and got this exception

```
[2021-06-04 03:24:25] production.ERROR: SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: "null" (SQL: select exists(select * from "medias" where "id" = null and "medias"."deleted_at" is null) as "exists") {"userId":1,"exception":"[object] (Illuminate\\Database\\QueryException(code: 22P02): SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: \"null\" (SQL: select exists(select * from \"medias\" where \"id\" = null and \"medias\".\"deleted_at\" is null) as \"exists\") at /workspace/vendor/laravel/framework/src/Illuminate/Database/Connection.php:685)
[stacktrace]
#0 /workspace/vendor/laravel/framework/src/Illuminate/Database/Connection.php(645): Illuminate\\Database\\Connection->runQueryCallback()
#1 /workspace/vendor/laravel/framework/src/Illuminate/Database/Connection.php(353): Illuminate\\Database\\Connection->run()
#2 /workspace/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2705): Illuminate\\Database\\Connection->select()
#3 /workspace/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1648): Illuminate\\Database\\Query\\Builder->exists()
#4 /workspace/vendor/area17/twill/src/Http/Controllers/Admin/MediaLibraryController.php(342): Illuminate\\Database\\Eloquent\\Builder->__call()
#5 /workspace/vendor/area17/twill/src/Http/Controllers/Admin/MediaLibraryController.php(214): A17\\Twill\\Http\\Controllers\\Admin\\MediaLibraryController->shouldReplaceMedia()
#6 /workspace/vendo
```

I saw that we have a wrapper that ensures $id must not be null in MediaLibraryController

```
    private function shouldReplaceMedia($id)
    {
        return isset($id) ? $this->repository->whereId($id)->exists() : false;
    }
```

### Expected result
Not pass to shouldReplaceMedia to true.

### Actual result
Still having defect SQL

### Versions

2.3

7.4

Posgresql

**Comment by weburnit** [comment]
Is it possible to do this?

```
    private function shouldReplaceMedia($id)
    {
        return $id > 0 ? $this->repository->whereId($id)->exists() : false;
    }
```
